version: "3"

services:
    web:
        build: ./
        ports:
            - "80:80"
        volumes:
            - ./src:/app/src/
            - .env:/app/.env

    db:
        image: mariadb
        container_name: chatDb
        restart: always
        volumes:
          - ./BD/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env.db
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
