CREATE TABLE chatJS
(
    idMessage INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contenu VARCHAR(255) NOT NULL,
    userPseudo VARCHAR(255) NOT NULL,
    horaire TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
